/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "var(--surface-container-low)",
        "on-secondary": "var(--on-secondary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-variant": "var(--surface-variant)",
        "background": "var(--background)",
        "on-surface": "var(--on-surface)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-dim": "var(--surface-dim)",
        "inverse-surface": "var(--inverse-surface)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "outline": "var(--outline)",
        "secondary": "var(--secondary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "secondary-container": "var(--secondary-container)",
        "on-background": "var(--on-background)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "primary": "var(--primary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface": "var(--surface)",
        "outline-variant": "var(--outline-variant)",
        "tertiary": "var(--tertiary)",
        "on-error": "var(--on-error)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container": "var(--surface-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "error": "var(--error)",
        "on-primary": "var(--on-primary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "surface-tint": "var(--surface-tint)",
        "on-tertiary": "var(--on-tertiary)",
        "on-error-container": "var(--on-error-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "primary-container": "var(--primary-container)",
        "error-container": "var(--error-container)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem"
      },
      spacing: {
        "stack-lg": "32px",
        "container-margin": "24px",
        "stack-md": "16px",
        "gutter": "16px",
        "stack-sm": "8px",
        "unit": "4px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "numeric-lg": ["JetBrains Mono", "monospace"],
        "display-tr": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "numeric-md": ["JetBrains Mono", "monospace"],
        "headline-tr": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "data-sm": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "data-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "data-lg": ["18px", {"lineHeight": "1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "numeric-lg": ["28px", {"lineHeight": "1", "fontWeight": "500"}],
        "display-tr": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "numeric-md": ["16px", {"lineHeight": "1", "fontWeight": "500"}],
        "headline-tr": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
